---
- name: Copier le fichier test.html dans le répertoire /var/www/html
  hosts: 172.16.20.52
  become: yes  # Utilise sudo si nécessaire pour avoir les privilèges d'écriture dans /var/www/html
  tasks:
    - name: Copier test.html sur le serveur
      copy:
        src: test.html  # Le chemin du fichier sur votre node manager
        dest: /var/www/html/test.html  # Le chemin de destination sur le serveur cible
        mode: '0644'  # Permet de s'assurer que le fichier est lisible
